### ISSUE TITLE
Jitpack failed to build with Build Tools 23.0.0 RC2

### ISSUE THREAD

**Issue by qk7b** [mcginty/material-colors#2]
As you can see here
https://jitpack.io/com/github/mcginty/material-colors/1.0.1/build.log

[jitpack](https://jitpack.io) failed to build the library because the _build tools are not installed_.
`failed to find Build Tools revision 23.0.0 rc2`

Please update build tools to the last version so the build can be run and used again.

Thanks,

**Comment by mcginty** [comment]
Thanks for the report!

**Comment by qk7b** [comment]
Closing it as `1.1.0` is now successful https://jitpack.io/com/github/mcginty/material-colors/1.1.0/build.log
